services:
  lb:
    image: ghcr.io/daniloitagyba/rinha-2026-dotnet:latest
    platform: linux/amd64
    build: .
    entrypoint: ["rinha-lb"]
    ports:
      - "9999:9999"
    volumes:
      - backend-sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.23"
          memory: "32MB"

  api1:
    image: ghcr.io/daniloitagyba/rinha-2026-dotnet:latest
    platform: linux/amd64
    build: .
    environment:
      BIND_ADDR: unix:/sockets/api1.sock
      INDEX_PATH: /app/data/references.idx
      SERVER_MODE: raw
      TP_MIN_THREADS: "128"
      WORKERS: "2"
      EARLY_CANDIDATES: "9800"
      MIN_CANDIDATES: "16150"
      MAX_CANDIDATES: "24200"
      PROFILE_FASTPATH: "1"
      PROFILE_MIN_COUNT: "15"
      PROFILE_LEGIT_MIN_COUNT: "5"
      PROFILE_FRAUD_MIN_COUNT: "15"
      EXACT_FALLBACK: "risky"
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.385"
          memory: "156MB"

  api2:
    image: ghcr.io/daniloitagyba/rinha-2026-dotnet:latest
    platform: linux/amd64
    build: .
    environment:
      BIND_ADDR: unix:/sockets/api2.sock
      INDEX_PATH: /app/data/references.idx
      SERVER_MODE: raw
      TP_MIN_THREADS: "128"
      WORKERS: "2"
      EARLY_CANDIDATES: "9800"
      MIN_CANDIDATES: "16150"
      MAX_CANDIDATES: "24200"
      PROFILE_FASTPATH: "1"
      PROFILE_MIN_COUNT: "15"
      PROFILE_LEGIT_MIN_COUNT: "5"
      PROFILE_FRAUD_MIN_COUNT: "15"
      EXACT_FALLBACK: "risky"
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.385"
          memory: "156MB"

volumes:
  backend-sockets:
