services:
  api1:
    entrypoint: ["rinha-fraud", "serve"]
    environment:
      KDTREE_NATIVE: "1"
      DOTNET_EnableDiagnostics: "0"

  api2:
    entrypoint: ["rinha-fraud", "serve"]
    environment:
      KDTREE_NATIVE: "1"
      DOTNET_EnableDiagnostics: "0"
